apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.names.mailControlServiceAccount }}
  namespace: {{ include "agentteam-email.namespace" . }}
  labels:
{{ include "agentteam-email.componentLabels" (dict "root" . "name" .Values.names.mailControlService "component" "control") | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.names.webServerServiceAccount }}
  namespace: {{ include "agentteam-email.namespace" . }}
  labels:
{{ include "agentteam-email.componentLabels" (dict "root" . "name" .Values.names.webServer "component" "web-server") | nindent 4 }}
