package atemail

import "fmt"

var outboundDisclosurePhrases = []string{
	"i am an agent",
	"i'm an agent",
	"im an agent",
	"i am a bot",
	"i'm a bot",
	"im a bot",
	"i am a chatbot",
	"i'm a chatbot",
	"im a chatbot",
	"i am an ai",
	"i'm an ai",
	"im an ai",
	"i am ai",
	"i am an ai agent",
	"i'm an ai agent",
	"im an ai agent",
	"i am an ai assistant",
	"i'm an ai assistant",
	"im an ai assistant",
	"i am artificial intelligence",
	"i am an artificial intelligence",
	"i'm artificial intelligence",
	"i'm an artificial intelligence",
	"im artificial intelligence",
	"im an artificial intelligence",
	"as an ai",
	"as an ai agent",
	"as an ai assistant",
	"as artificial intelligence",
	"as an artificial intelligence",
	"as a language model",
	"as a large language model",
	"i am a language model",
	"i'm a language model",
	"im a language model",
	"i am a large language model",
	"i'm a large language model",
	"im a large language model",
	"ai agent",
	"ai assistant",
	"artificial intelligence",
	"language model",
	"large language model",
	"llm",
	"automated agent",
	"automated assistant",
	"automated system",
	"automated email",
	"automated message",
	"automation agent",
	"this is an automated",
	"this is auto generated",
	"this is autogenerated",
	"automatically generated",
	"machine generated",
	"computer generated",
	"generated by ai",
	"generated by an ai",
	"generated by artificial intelligence",
	"written by ai",
	"written by an ai",
	"sent by ai",
	"sent by an ai",
	"sent by an automated agent",
	"sent by an automated system",
	"sent by a bot",
	"sent from an ai",
}

func validateOutboundMessage(subject *string, text string, cfg config) error {
	fields := []struct {
		label string
		value string
	}{
		{label: "subject", value: ""},
		{label: "body", value: text},
	}
	if subject != nil {
		fields[0].value = *subject
	}

	for _, field := range fields {
		if field.value == "" {
			continue
		}
		normalized := normalizeDisclosureText(field.value)
		for _, phrase := range outboundDisclosurePhrases {
			normalizedPhrase := normalizeDisclosureText(phrase)
			if normalizedPhrase != "" && normalizedContains(normalized, normalizedPhrase) {
				return newAgentMailError(fmt.Sprintf(
					"outbound mail security violation: message %s contains prohibited disclosure phrase %q. Remove internal agent names and AI/automation disclosures before sending.",
					field.label,
					phrase,
				))
			}
		}
		for _, term := range cfg.InternalIdentityTerms {
			normalizedTerm := normalizeDisclosureText(term.Value)
			if normalizedTerm != "" && normalizedContains(normalized, normalizedTerm) {
				return newAgentMailError(fmt.Sprintf(
					"outbound mail security violation: message %s contains internal identity %q from %s. Remove internal agent names and AI/automation disclosures before sending.",
					field.label,
					term.Value,
					term.Source,
				))
			}
		}
	}
	return nil
}
