# Docker Compose local image build override.
# Use with compose.yaml:
# docker compose -f compose.yaml -f compose.build.yaml up -d --build

services:
  atemail-mail-control-service:
    pull_policy: build
    image: 'atemail.${WT:-main}.mail-control-service:stage'
    build:
      context: ./apps/mail-control-service
      dockerfile: Containerfile
      args:
        APP_UID: '${AT_EMAIL_ADMIN_UID:-1000}'
        APP_GID: '${AT_EMAIL_ADMIN_GID:-1000}'

  atemail-web-server:
    pull_policy: build
    image: 'atemail.${WT:-main}.web-server:stage'
    build:
      context: .
      dockerfile: apps/web-server/Containerfile
      args:
        APP_UID: '${AT_EMAIL_ADMIN_UID:-1000}'
        APP_GID: '${AT_EMAIL_ADMIN_GID:-1000}'
