mongo = "{{ include "agentteam-email.mongodbUri" (dict "root" . "database" "wildduck" "options" "maxPoolSize=4&minPoolSize=0&maxIdleTimeMS=60000") }}"
redis = "redis://{{ .Values.names.redis }}:6379/3"
sender = "wildduck"
