mongo = "{{ include "agentteam-email.mongodbUri" (dict "root" . "database" "wildduck" "options" (include "agentteam-email.mongodbClientOptions" (dict "pool" .Values.mongodb.clientPools.wildduck))) }}"
redis = "redis://{{ .Values.names.redis }}:6379/3"
sender = "wildduck"
