/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificationEmailSentRouteImport } from './routes/verification-email-sent'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignoutRouteImport } from './routes/signout'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoveryEmailSentRouteImport } from './routes/recovery-email-sent'
import { Route as RecoverAccountRouteImport } from './routes/recover-account'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DeviceRouteImport } from './routes/device'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RedirectErrorRouteImport } from './routes/redirect/error'
import { Route as DeviceCapabilitiesRouteImport } from './routes/device/capabilities'
import { Route as DeviceApproveRouteImport } from './routes/device/approve'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AgentClaimTokenRouteImport } from './routes/agent/claim.$token'
import { Route as AuthenticatedSettingsSectionRouteImport } from './routes/_authenticated/settings.$section'
import { Route as AuthenticatedOrganizationSectionRouteImport } from './routes/_authenticated/organization.$section'

const VerificationEmailSentRoute = VerificationEmailSentRouteImport.update({
  id: '/verification-email-sent',
  path: '/verification-email-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignoutRoute = SignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryEmailSentRoute = RecoveryEmailSentRouteImport.update({
  id: '/recovery-email-sent',
  path: '/recovery-email-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverAccountRoute = RecoverAccountRouteImport.update({
  id: '/recover-account',
  path: '/recover-account',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceRoute = DeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const RedirectErrorRoute = RedirectErrorRouteImport.update({
  id: '/redirect/error',
  path: '/redirect/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeviceCapabilitiesRoute = DeviceCapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => DeviceRoute,
} as any)
const DeviceApproveRoute = DeviceApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => DeviceRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AgentClaimTokenRoute = AgentClaimTokenRouteImport.update({
  id: '/agent/claim/$token',
  path: '/agent/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsSectionRoute =
  AuthenticatedSettingsSectionRouteImport.update({
    id: '/$section',
    path: '/$section',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedOrganizationSectionRoute =
  AuthenticatedOrganizationSectionRouteImport.update({
    id: '/organization/$section',
    path: '/organization/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/callback': typeof CallbackRoute
  '/device': typeof DeviceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/magic-link': typeof MagicLinkRoute
  '/recover-account': typeof RecoverAccountRoute
  '/recovery-email-sent': typeof RecoveryEmailSentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/verification-email-sent': typeof VerificationEmailSentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/device/approve': typeof DeviceApproveRoute
  '/device/capabilities': typeof DeviceCapabilitiesRoute
  '/redirect/error': typeof RedirectErrorRoute
  '/admin/': typeof AdminIndexRoute
  '/organization/$section': typeof AuthenticatedOrganizationSectionRoute
  '/settings/$section': typeof AuthenticatedSettingsSectionRoute
  '/agent/claim/$token': typeof AgentClaimTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/callback': typeof CallbackRoute
  '/device': typeof DeviceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/magic-link': typeof MagicLinkRoute
  '/recover-account': typeof RecoverAccountRoute
  '/recovery-email-sent': typeof RecoveryEmailSentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/verification-email-sent': typeof VerificationEmailSentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/device/approve': typeof DeviceApproveRoute
  '/device/capabilities': typeof DeviceCapabilitiesRoute
  '/redirect/error': typeof RedirectErrorRoute
  '/admin': typeof AdminIndexRoute
  '/organization/$section': typeof AuthenticatedOrganizationSectionRoute
  '/settings/$section': typeof AuthenticatedSettingsSectionRoute
  '/agent/claim/$token': typeof AgentClaimTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/callback': typeof CallbackRoute
  '/device': typeof DeviceRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/magic-link': typeof MagicLinkRoute
  '/recover-account': typeof RecoverAccountRoute
  '/recovery-email-sent': typeof RecoveryEmailSentRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signout': typeof SignoutRoute
  '/signup': typeof SignupRoute
  '/verification-email-sent': typeof VerificationEmailSentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/device/approve': typeof DeviceApproveRoute
  '/device/capabilities': typeof DeviceCapabilitiesRoute
  '/redirect/error': typeof RedirectErrorRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/organization/$section': typeof AuthenticatedOrganizationSectionRoute
  '/_authenticated/settings/$section': typeof AuthenticatedSettingsSectionRoute
  '/agent/claim/$token': typeof AgentClaimTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/accept-invite'
    | '/callback'
    | '/device'
    | '/forgot-password'
    | '/magic-link'
    | '/recover-account'
    | '/recovery-email-sent'
    | '/reset-password'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/verification-email-sent'
    | '/dashboard'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/setup'
    | '/device/approve'
    | '/device/capabilities'
    | '/redirect/error'
    | '/admin/'
    | '/organization/$section'
    | '/settings/$section'
    | '/agent/claim/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/callback'
    | '/device'
    | '/forgot-password'
    | '/magic-link'
    | '/recover-account'
    | '/recovery-email-sent'
    | '/reset-password'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/verification-email-sent'
    | '/dashboard'
    | '/settings'
    | '/admin/audit-logs'
    | '/admin/setup'
    | '/device/approve'
    | '/device/capabilities'
    | '/redirect/error'
    | '/admin'
    | '/organization/$section'
    | '/settings/$section'
    | '/agent/claim/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/accept-invite'
    | '/callback'
    | '/device'
    | '/forgot-password'
    | '/magic-link'
    | '/recover-account'
    | '/recovery-email-sent'
    | '/reset-password'
    | '/signin'
    | '/signout'
    | '/signup'
    | '/verification-email-sent'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/admin/audit-logs'
    | '/admin/setup'
    | '/device/approve'
    | '/device/capabilities'
    | '/redirect/error'
    | '/admin/'
    | '/_authenticated/organization/$section'
    | '/_authenticated/settings/$section'
    | '/agent/claim/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  CallbackRoute: typeof CallbackRoute
  DeviceRoute: typeof DeviceRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MagicLinkRoute: typeof MagicLinkRoute
  RecoverAccountRoute: typeof RecoverAccountRoute
  RecoveryEmailSentRoute: typeof RecoveryEmailSentRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignoutRoute: typeof SignoutRoute
  SignupRoute: typeof SignupRoute
  VerificationEmailSentRoute: typeof VerificationEmailSentRoute
  RedirectErrorRoute: typeof RedirectErrorRoute
  AgentClaimTokenRoute: typeof AgentClaimTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verification-email-sent': {
      id: '/verification-email-sent'
      path: '/verification-email-sent'
      fullPath: '/verification-email-sent'
      preLoaderRoute: typeof VerificationEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signout': {
      id: '/signout'
      path: '/signout'
      fullPath: '/signout'
      preLoaderRoute: typeof SignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-email-sent': {
      id: '/recovery-email-sent'
      path: '/recovery-email-sent'
      fullPath: '/recovery-email-sent'
      preLoaderRoute: typeof RecoveryEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-account': {
      id: '/recover-account'
      path: '/recover-account'
      fullPath: '/recover-account'
      preLoaderRoute: typeof RecoverAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device': {
      id: '/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof DeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/redirect/error': {
      id: '/redirect/error'
      path: '/redirect/error'
      fullPath: '/redirect/error'
      preLoaderRoute: typeof RedirectErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/device/capabilities': {
      id: '/device/capabilities'
      path: '/capabilities'
      fullPath: '/device/capabilities'
      preLoaderRoute: typeof DeviceCapabilitiesRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/device/approve': {
      id: '/device/approve'
      path: '/approve'
      fullPath: '/device/approve'
      preLoaderRoute: typeof DeviceApproveRouteImport
      parentRoute: typeof DeviceRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/agent/claim/$token': {
      id: '/agent/claim/$token'
      path: '/agent/claim/$token'
      fullPath: '/agent/claim/$token'
      preLoaderRoute: typeof AgentClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/$section': {
      id: '/_authenticated/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AuthenticatedSettingsSectionRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/organization/$section': {
      id: '/_authenticated/organization/$section'
      path: '/organization/$section'
      fullPath: '/organization/$section'
      preLoaderRoute: typeof AuthenticatedOrganizationSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsSectionRoute: typeof AuthenticatedSettingsSectionRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsSectionRoute: AuthenticatedSettingsSectionRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedOrganizationSectionRoute: typeof AuthenticatedOrganizationSectionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedOrganizationSectionRoute: AuthenticatedOrganizationSectionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DeviceRouteChildren {
  DeviceApproveRoute: typeof DeviceApproveRoute
  DeviceCapabilitiesRoute: typeof DeviceCapabilitiesRoute
}

const DeviceRouteChildren: DeviceRouteChildren = {
  DeviceApproveRoute: DeviceApproveRoute,
  DeviceCapabilitiesRoute: DeviceCapabilitiesRoute,
}

const DeviceRouteWithChildren =
  DeviceRoute._addFileChildren(DeviceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  CallbackRoute: CallbackRoute,
  DeviceRoute: DeviceRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MagicLinkRoute: MagicLinkRoute,
  RecoverAccountRoute: RecoverAccountRoute,
  RecoveryEmailSentRoute: RecoveryEmailSentRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignoutRoute: SignoutRoute,
  SignupRoute: SignupRoute,
  VerificationEmailSentRoute: VerificationEmailSentRoute,
  RedirectErrorRoute: RedirectErrorRoute,
  AgentClaimTokenRoute: AgentClaimTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
