mongo = "{{ include "agentteam-email.mongodbUri" (dict "root" . "database" "wildduck" "options" "maxPoolSize=4&minPoolSize=0&maxIdleTimeMS=60000") }}"
sender = "wildduck"

[redis]
host = "{{ .Values.names.redis }}"
port = 6379
db = 3
