mongo = "mongodb://{{ .Values.names.mongodb }}:27017/wildduck?directConnection=true&maxPoolSize=4&minPoolSize=0&maxIdleTimeMS=60000"
sender = "wildduck"

[redis]
host = "{{ .Values.names.redis }}"
port = 6379
db = 3
