mongo = "{{ include "agentteam-email.mongodbUri" (dict "root" . "database" "wildduck" "options" (include "agentteam-email.mongodbClientOptions" (dict "pool" .Values.mongodb.clientPools.wildduck))) }}"
sender = "wildduck"

[redis]
host = "{{ .Values.names.redis }}"
port = 6379
db = 3
